[window]
dimensions = {columns = 80, lines = 24}
dynamic_title = true
decorations_theme_variant = "None"
decorations = "Full"
opacity = 1

[font]
normal = {family = "Sauce Code Pro Nerd Font", style = "Regular"}
bold = {family = "Sauce Code Pro Nerd Font", style = "Bold" }
size = 7

[colors]
primary = {background = "#262626", foreground = "#FFFFFF"}

